# Numpy

In [3]:
import numpy as np

In [4]:
x = np.arange(27)

print(x.shape)
print(x.ndim)
print(x.size)
print(x.nbytes)
y = x.tolist()
print(y)
print(x.reshape((3,3,3)))
x.sort()
print(x.max())

(27,)
1
27
108
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
26


# Pandas

In [32]:
import os
import pandas as pd
import numpy as np

os.chdir("E:")
file_csv = pd.read_csv("SalesJan2009.csv")
print(file_csv)

# check datatype of each column
print(file_csv.dtypes)
file_csv.dtypes.value_counts() #return counts of unique datatypes in data frames

#return a subset of column based on their datatypes 
#we can use include to indicate needed column or exclude with datatype to avoid that columns
print(file_csv.select_dtypes(exclude=[object]))

#give a summary of dataframe types of index,column,count of not null-values,memory usage 
print(file_csv.info())
  
#to find unique elements of a column
print(np.unique(file_csv['Country']))


    Transaction_date   Product Price Payment_Type               Name  \
0        1/2/09 6:17  Product1  1200   Mastercard           carolina   
1        1/2/09 4:53  Product1  1200         Visa             Betina   
2       1/2/09 13:08  Product1  1200   Mastercard  Federica e Andrea   
3       1/3/09 14:44  Product1  1200         Visa              Gouya   
4       1/4/09 12:56  Product2  3600         Visa            Gerd W    
..               ...       ...   ...          ...                ...   
993    1/22/09 14:25  Product1  1200         Visa         Hans-Joerg   
994     1/28/09 5:36  Product2  3600         Visa         Christiane   
995      1/1/09 4:24  Product3  7500         Amex             Pamela   
996     1/8/09 11:55  Product1  1200       Diners              julie   
997    1/12/09 21:30  Product1  1200         Visa             Julia    

                             City             State         Country  \
0                        Basildon           England  United King

# Random

In [8]:
import random as rand

In [10]:
rand.randrange(5)

0

In [11]:
rand.randint(1,50)

32

In [13]:
rand.getrandbits(5)

12

In [20]:
mylist = ["apple", "banana", "cherry"]
rand.choices(mylist, weights = [10, 1, 1], k = 14)

['apple',
 'apple',
 'banana',
 'apple',
 'banana',
 'apple',
 'banana',
 'apple',
 'apple',
 'apple',
 'apple',
 'apple',
 'apple',
 'apple']

In [26]:
list_1 = 'My name is Shreya.'.split()
rand.shuffle(list_1)
print(list_1)

['Shreya.', 'name', 'My', 'is']


In [28]:
rand.uniform(1.0,5.0)

4.980089935804122

In [29]:
rand.random()

0.7902061611460349

In [34]:
import random
a = [1,2,3]
print(random.choice(a))

3


In [35]:
print(random.randint(1,10))

8


# Random Task:1 OTP Generato

In [36]:
length = int(input("Enter Length: "))

num = "0123456789"
print("".join(random.sample(num,length)))

Enter Length: 5
61205


# Random Task:2 Password Generator

In [37]:
import random as rand

digit= ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'] 
locase = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h','i', 'j', 'k', 'm', 'n', 'o', 'p', 'q',
                     'r', 's', 't', 'u', 'v', 'w', 'x', 'y','z']
upcase = list(map(lambda x:x.upper(), locase))
sym = ['@', '#', '$', '%', '=', ':', '?', '.', '/', '|', '~', '>','*', '(', ')', '<']

r_digit = rand.choices(digit)
r_upcase = rand.choices(upcase)
r_locase = rand.choices(locase)
r_sym = rand.choices(sym)

r_com = r_digit + r_locase + r_upcase + r_sym
com_list = digit + locase + upcase + sym

length = int(input("Enter length of password(>=4): "))
for i in range(length - 4):
    r_com += rand.choices(com_list)
    
password = ""
for j in r_com:
        password = password + j
         
print(password)

Enter length of password(>=4): 5
1aH).


# gTTS

In [38]:
pip install gtts

You should consider upgrading via the 'c:\users\shreya\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.



  Using cached gTTS-2.2.2-py3-none-any.whl (25 kB)


In [1]:
from gtts import gTTS

In [6]:
a = gTTS("Hello, My name is Shreya")

In [8]:
gTTS.get_bodies(a)

['f.req=%5B%5B%5B%22jQ1olc%22%2C%22%5B%5C%22Hello%2C%20My%20name%20is%20Shreya%5C%22%2C%5C%22en%5C%22%2Cnull%2C%5C%22null%5C%22%5D%22%2Cnull%2C%22generic%22%5D%5D%5D&']

In [5]:
a.save("voice.mp3")

In [1]:
from gtts import gTTS

text_no = int(input("How many lines you want to add"))

with open('voice.mp3', 'wb') as f:
    for i in range(text_no):
        text = input("Enter line:")
        tts = gTTS(text)
        tts.write_to_fp(f)


How many lines you want to add3
Enter line:Hey
Enter line:Im sreya 
Enter line:I am at kapadvanj.


In [29]:
from gtts import gTTS
from io import BytesIO
mp3_fp = BytesIO()
tts = gTTS('hello', lang='en')
tts.write_to_fp(mp3_fp)

In [27]:
from gtts import gTTS
from tempfile import TemporaryFile
tts = gTTS(text='Hello', lang='en')
f = TemporaryFile()
tts.write_to_fp(f)

In [28]:
from gtts import gTTS
from io import BytesIO

my_variable = 'hello' # your real code gets this from the chatbot

mp3_fp = BytesIO()
tts = gTTS(my_variable, 'en')
tts.write_to_fp(mp3_fp)


gTTSError: Failed to connect. Probable cause: Host 'https://translate.google.en/' is not reachable